### ISSUE TITLE
Client never gets message

### ISSUE THREAD

**Issue by CD1010** [Layla-P/RabbitMQTopicExchange#1]
Ran this sample from complete branch and i cannot get it to run.
Ran docker container first
Startup OrderService, then kitchenservice.

In debugger, i see the message getting published. In client, i put a breakpoint on receiver handler, but it never gets the message.

I do notice rabbitmq is getting the message and creating the exchange though.
topic looks like matches in both places.

Rabbit samples do work and travel through container just fine.  Something is up with your sample.

**Comment by Layla-P** [comment]
Hi @CD1010 
First, thank you for trying out the code and I apologise that it has not gone to plan.
I just merged start into main after updating a name.
I just cloned the repo afresh and ran the completed branch. I have no errors and the message appears on kitchen UI.

Could you try cloning the updated repo and running the completed branch again to see if that has sorted your issue?

Layla
